site_name: Static HTML Builder

theme: readthedocs

pages:
  - [index.md, Home]
  - [getting-started.md, 开始使用]
  - [tutorial.md, 教程]
  - [release.md, 版本历史]
  - [cordova.md, cordova打包帮助]

repo_url: https://github.com/gengen1988/static-html-builder

google_analytics: ['UA-62410339-1', 'auto']
